spring:
  application:
    name: payment-initiator
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  datasource:
    url: jdbc:h2:mem:pi_outbox;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  h2:
    console:
      enabled: true
      path: /h2-console


server:
  port: ${PORT:8097}

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus"

info:
  app:
    description: Payment Initiator Microservice
    version: 1.0

eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8070/eureka/}

logging:
  level:
    root: INFO
    com.harshalmayee.paymentinitiator: INFO
